### ISSUE TITLE
subdirectory WiringPi is empty

### ISSUE THREAD

**Issue by andybr1** [WiringPi/WiringPi-Perl#2]
When I cloned WiringPi-Perl the sub directory WiringPi remained empty. I needed to clone WiringPi additionally into the directory. Not sure whether this is the intended use or correct. If yes it would be worth adding it to the README

**Comment by gevrey** [comment]
Same here.

**Comment by gevrey** [comment]
The version of Perl needs to be updated in the build.sh script to have the correct include path.

**Comment by Gadgetoid** [comment]
You need to update the git submodules with the following command:

```
git submodule update --init
```
