### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by ap0calypse** [WiringPi/WiringPi-Perl#5]
Hi,

I tried to compile and install your module, but unfortunately I can't make it work here. I have a Raspberry Pi 2 Model B. I 'git clone'd the wiringpi-perl repo and inside this repo cloned the normal wiringpi libs. so far it seemed to work. But serial.h is missing. Even if I rename wiringSerial.h to serial.h (or vice versa) it doesn't work.

The error seems to be in wiringpi_wrap.c 
I get several errors like this:

/usr/lib/perl5/core_perl/CORE/handy.h:124:34: error: 'bool' uindeclared (first use in this function) ....
yadda yadda....

I had to rewrite the build.sh script to use my correct perl path here, but there seems to be an inconistency between versions afaics.

regards,
manuel

**Comment by karstengit** [comment]
This error can really be fixed when you simply copy wiringSerial.h to serial.h.
Then it compiles but you get another error when you try to use the module.
https://github.com/WiringPi/WiringPi-Perl/issues/6

Could you get the module to fly?
